# Generated by Django 4.0.6 on 2022-08-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('classs', models.CharField(choices=[('MCA1', 'MCA1'), ('MBA1', 'MBA2'), ('MCA2', 'MCA2')], max_length=50)),
                ('division', models.CharField(choices=[('Codeworroers', 'Codeworroers'), ('Technocrats', 'Technocrats')], max_length=50)),
                ('rollno', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('macaddress', models.FloatField()),
                ('parentmobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
