# Generated by Django 4.0.6 on 2022-08-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classs',
            field=models.CharField(choices=[('MCA1', 'MCA1'), ('MBA1', 'MBA1'), ('MCA2', 'MCA2'), ('MBA2', 'MBA2')], max_length=50),
        ),
    ]
