# Generated by Django 4.0.6 on 2022-08-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofence', '0002_alter_student_classs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(choices=[('Codewarroiers', 'Codewarroiers'), ('Technocrats', 'Technocrats')], max_length=50),
        ),
    ]
