# Generated by Django 4.0.6 on 2022-08-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geofence', '0006_inout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
