# Generated by Django 4.0.6 on 2022-08-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofence', '0008_studententry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studententry',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
